const ROLE = {
   ADMIN: '1',
   SUPPORTER: '2',
   CUSTOMER: '0',
};

const STATUS_CODE = {
   OK: 200,
   CREATED: 201,
   BAD_REQUEST: 400,
   UNAUTHORIZED: 401,
   FORBIDDEN: 403,
   NOT_FOUND: 404,
   CONFLICT: 409,
   INTERFACE_SERVER_ERROR: 500,
};

module.exports = { ROLE, STATUS_CODE };
